vim.filetype.add({
    extension = {
        dockerfile = "dockerfile",
        automount = "systemd",
        mount = "systemd",
        path = "systemd",
        service = "systemd",
        socket = "systemd",
        swap = "systemd",
        target = "systemd",
        timer = "systemd",
        log = "log",
        LOG = "log",
        _log = "log",
        _LOG = "log",
    },
    pattern = {
        ["*%.snip"] = "vim",
        ["*%.nginx"] = "nginx",
        [".*nginx.*%.conf"] = "nginx",
        [".*nginx/.*/conf.*"] = "nginx",
        [".*/nginx/.*%.conf"] = "nginx",
        ["/srv/nginx/conf%.d/locations/.*"] = "nginx",
    },
})
